version: "3.7"
services:
  university:
    image: ${REPO}/${CONTAINER}:${TAG}
    container_name: ${CONTAINER}
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ~/volumes/university:/usr/src/app/logs
      - ~/volumes/university/upload:/usr/src/app/university/upload
      - ~/etc/timezone:/etc/localtime:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - ${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
    networks: 
      - nginx
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ~/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: deployer
      MYSQL_PASSWORD: Password@1
    ports:
      - "3306:3306"
    networks:
      - nginx
networks:
  nginx:
    external: true
    name: nginx